apiVersion: apps/v1
kind: Deployment
metadata:
  name: customvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customvision
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: customvision
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: customvision
        image: tsukatoh.azurecr.io/customvision:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: customvision
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: customvision
